name = "chatkit-token"
main = "worker/worker.js"
compatibility_date = "2024-11-01"

[vars]
WORKFLOW_ID = "wf_69018a6adb788190b3f0a1023ee8f1640a7d5f6cb4dd077f"
CHATKIT_VERSION = "2"
ALLOWED_ORIGIN = "https://kaimaekawa-byte.github.io"
